// Login actions
export const ACTION_LOGIN = "@AUTH/ACTION_LOGIN";
export const ACTION_LOGOUT = "@AUTH/ACTION_LOGOUT";
export const ACTION_REFRESH_TOKEN = "@AUTH/ACTION_REFRESH_TOKEN";

export default {
  ACTION_LOGIN,
  ACTION_LOGOUT,
  ACTION_REFRESH_TOKEN
};
